name: workflow dispath 
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'    
        required: true
        default: ''
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Job time range arg: ${{ github.event.inputs.time_window }}"
          echo "Job run manually?: ${{ github.event.inputs.manual }}"        
