name: Maven-Docker-Build

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  build:
    name: Maven-Build-and-Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Bulind and testing the code
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
    
    # Let's cache the dependencies to speed up workflow
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2    
     
     # For testing          
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      
      # Let's packages the workflow data as artifacts
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
            name: Package
            path: staging          
  
  docker:
    name: build-image-and-publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ameendocker/gitactiondemo:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
