name: PRbuildAndPush

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 5
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Build and push 

      - name: Lgoing to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Define image metadata
        id:  docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ameendocker/testapp
          tags: |
            ${{ github.event.inputs.tag }}
          labels: |
            org.opencontainers.image.authors=test/ASPA
            org.opencontainers.image.vendor=jyu


      - name: Build image and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: false
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ github.event.pull_request.head.sha }}

# To get those as artifect 

  parse-and-store-pr-name:
    runs-on: ubuntu-latest 
    timeout-minutes: 2
    needs: [ build-image ]

    steps:
      - name: Parse PR name
        run: |
          echo "PR name $PR_TITLE"
          echo "GHA-Hello-$(echo ${PR_TITLE// /-} | tr '[:upper:]' '[:lower:]')" > parsed-pr-name.txt
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Upload PR name
        uses: actions/upload-artifact@v2
        with:
          name: parsed_pr_name
          path: parsed-pr-name.txt
