name: PRbuildAndPush

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Create artifact files
        run: |
          mkdir -p ~/new/artifact
          echo Hello Ameen, this is artifact testing > ~/new/artifact/world.txt
          mkdir -p ~/new2/artifact2
          echo "This is another one! " > ~/new2/artifact2/another.txt
          
      - uses: actions/upload-artifact@v2
        with:	
          name: 'Artifacts'	
          path: '~/new/**/*'
      
