 # Build and push 

      - name: Lgoing to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Define image metadata
        id:  docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ameendocker/testapp
          tags: |
            ${{ github.event.inputs.tag }}
          labels: |
            org.opencontainers.image.authors=test/ASPA
            org.opencontainers.image.vendor=jyu


      - name: Build image and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: false
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ github.event.pull_request.head.sha }}
